import Layout from '@/components/Layout'
import { CommerceProvider } from '@/hooks/useCommerce'
import type { Metadata } from 'next'
import type { AppProps } from 'next/app'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from 'styled-components'
import '../styles.css'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const theme = {
  background: '#2F2E41',
  primaryColor: '#009EDD',
  secondaryColor: '#039B00',
  textPrimaryColor: '#FFFFFF',
  textSecondaryColor: '#999999',
}
export type ITheme = typeof theme

export default function RootLayout({ Component, pageProps }: AppProps) {
  return (
    <main className={openSans.className}>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
      />

      <ThemeProvider theme={theme}>
        <CommerceProvider>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </CommerceProvider>
      </ThemeProvider>
    </main>
  )
}
