import Layout from '@/components/Layout'
import { CommerceProvider } from '@/hooks/useCommerce'
import type { Metadata } from 'next'
import type { AppProps } from 'next/app'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from 'styled-components'
import '../styles.css'
import { DefaultTheme } from 'styled-components/dist/types'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const theme: DefaultTheme = {
  background: '#2F2E41',
  cardBackground: '#FFFFFF',

  primaryColor: '#009EDD',
  secondaryColor: '#039B00',

  textCardColor: '#2F2E41',
  textPrimaryColor: '#FFFFFF',
  textSecondaryColor: '#999999',

  borderInputColor: '#D9D9D9',
  borderColor: '#999999',
}

export default function RootLayout({ Component, pageProps }: AppProps) {
  return (
    <main className={openSans.className}>
      <ThemeProvider theme={theme}>
        <CommerceProvider>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </CommerceProvider>
      </ThemeProvider>
    </main>
  )
}
