import { CommerceProvider } from "@/hooks/useCommerce";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ Component, pageProps }: Readonly<{
  Component: any
  pageProps: any
}>) {
  return (
    <main className={openSans.className}>
      <CommerceProvider>
        <Component {...pageProps} />
      </CommerceProvider>
    </main>

  );
}
